Assumption: we have an input text of 6 words, and each word is represented by a 512 dimension vector.

In this case, the $sequence = 6$ and $d_{model} = 512$.

Therefore:

$\text{Input matrix} (sequence, d_{model}) = (6, 512)$

Let's assume that our words are:

$\text{A, B, C, D, E, F}$

Then, the illustration of the input matrix looks like this:

$$
\text{Input matrix} = \begin{bmatrix}
\text{A}, & \text{B}, & \text{C}, & \text{D}, & \text{E}, & \text{F} \\
\end{bmatrix}
$$


Let's assume that each word has the following 512 columns of numerical representation (basically acting like 512 dimensions):

$$

\text{word} = \begin{bmatrix}
W_{0},  & W_{1}, & W_{2}, & \dots & W_{511} \\
\end{bmatrix}
$$

Note that each $W_{i}$ here is a number.

With this background, the input matrix (let's call it $W$) in an expanded form should look like this:

$$
W = \begin{bmatrix}
\begin{bmatrix} \text{A}_0, & \text{A}_1, & \text{A}_2, & \dots, & \text{A}_{511} \end{bmatrix} \\
\begin{bmatrix} \text{B}_0, & \text{B}_1, & \text{B}_2, & \dots, & \text{B}_{511} \end{bmatrix} \\
\begin{bmatrix} \text{C}_0, & \text{C}_1, & \text{C}_2, & \dots, & \text{C}_{511} \end{bmatrix} \\
\begin{bmatrix} \text{D}_0, & \text{D}_1, & \text{D}_2, & \dots, & \text{D}_{511} \end{bmatrix} \\
\begin{bmatrix} \text{E}_0, & \text{E}_1, & \text{E}_2, & \dots, & \text{E}_{511} \end{bmatrix} \\
\begin{bmatrix} \text{F}_0, & \text{F}_1, & \text{F}_2, & \dots, & \text{F}_{511} \end{bmatrix}
\end{bmatrix}
$$

The shape, as we can clearly see, is $(6, 512)$.

Also, the transpose of this looks like this:

$$
W^\text{T} = \begin{bmatrix}
\begin{bmatrix} \text{A}_0, & \text{B}_0, & \text{C}_0, & \text{D}_0, & \text{E}_0, & \text{F}_0 \end{bmatrix} \\
\begin{bmatrix} \text{A}_1, & \text{B}_1, & \text{C}_1, & \text{D}_1, & \text{E}_1, & \text{F}_1 \end{bmatrix} \\
\begin{bmatrix} \text{A}_2, & \text{B}_2, & \text{C}_2, & \text{D}_2, & \text{E}_2, & \text{F}_2 \end{bmatrix} \\
\begin{bmatrix} \text{A}_3, & \text{B}_3, & \text{C}_3, & \text{D}_3, & \text{E}_3, & \text{F}_3 \end{bmatrix} \\
\vdots \\
\begin{bmatrix} \text{A}_{511}, & \text{B}_{511}, & \text{C}_{511}, & \text{D}_{511}, & \text{E}_{511}, & \text{F}_{511} \end{bmatrix}
\end{bmatrix}
$$

The shape of this is $(512, 6)$.

In [1]:
import torch
import torch.nn as nn

In [2]:
torch.manual_seed(40)
input_matrix = torch.randn(6, 512)
input_matrix.shape, input_matrix

(torch.Size([6, 512]),
 tensor([[-0.2367,  1.8109,  0.1966,  ..., -0.6320,  0.3352,  0.3928],
         [ 0.0783,  0.5694, -0.6083,  ...,  0.3377,  0.9911, -1.0636],
         [ 0.0525, -0.4094, -0.7481,  ...,  0.7475, -1.0518, -0.2402],
         [-0.7422,  0.5986,  1.1324,  ...,  0.6658, -1.9029,  0.3874],
         [ 0.3757, -0.0370,  0.0536,  ...,  1.3480, -0.3502,  1.4096],
         [ 0.3379,  0.6135,  0.3060,  ..., -0.1643, -1.4237,  1.1242]]))

In [3]:
input_matrix.T.shape, input_matrix.T

(torch.Size([512, 6]),
 tensor([[-0.2367,  0.0783,  0.0525, -0.7422,  0.3757,  0.3379],
         [ 1.8109,  0.5694, -0.4094,  0.5986, -0.0370,  0.6135],
         [ 0.1966, -0.6083, -0.7481,  1.1324,  0.0536,  0.3060],
         ...,
         [-0.6320,  0.3377,  0.7475,  0.6658,  1.3480, -0.1643],
         [ 0.3352,  0.9911, -1.0518, -1.9029, -0.3502, -1.4237],
         [ 0.3928, -1.0636, -0.2402,  0.3874,  1.4096,  1.1242]]))

In [4]:
transpose_dotproduct = input_matrix @ input_matrix.T
transpose_dotproduct.shape, transpose_dotproduct

(torch.Size([6, 6]),
 tensor([[503.2782,  30.9015, -25.3849,  13.0093, -29.7297,  20.1604],
         [ 30.9015, 536.9385, -23.3817, -70.6838,  -8.7096, -19.2283],
         [-25.3849, -23.3817, 484.9792,  24.6444, -29.3236,  -0.9737],
         [ 13.0093, -70.6838,  24.6444, 538.0654, -25.3541,  -8.6208],
         [-29.7297,  -8.7096, -29.3236, -25.3541, 453.2016,  -5.3324],
         [ 20.1604, -19.2283,  -0.9737,  -8.6208,  -5.3324, 539.1165]]))

In [5]:
A = input_matrix[0][:] # first row
A @ A.T # basically dot product of A and A^T

/var/folders/27/84mpvnn15tlby6jt5y456k5c0000gn/T/ipykernel_49899/3060185599.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3729.)
  A @ A.T # basically dot product of A and A^T


tensor(503.2783)

## Positional Encoding

Formulas for positional encoding in the original transformer paper are:

$$
\begin{aligned}
PE_{(pos, 2i)} &= \sin\left(\frac{pos}{10000^{2i/d_{\text{model}}}}\right) \quad \text{(even indices)} \\
PE_{(pos, 2i+1)} &= \cos\left(\frac{pos}{10000^{2i/d_{\text{model}}}}\right) \quad \text{(odd indices)}
\end{aligned}
$$

where $pos$ is the position of the word in the sentence, and $i$ is the dimension index (starting from 0 to $d_{model} - 1$).









## Multi-Head Attention

Formula for multi-head attention in the original transformer paper is:

$$
\text{MultiHead}(Q, K, V) = \text{Concat}(\text{head}_1, \text{head}_2, \dots, \text{head}_h)W^\text{O}
$$

where:

$
\text{head}_i = \text{Attention}(QW_i^Q, KW_i^K, VW_i^V)
$

where $W_i^Q, W_i^K, W_i^V$ are the weights for the $i$-th head.

and:

$
W^\text{O} = \begin{bmatrix}
W_1^\text{O}, & W_2^\text{O}, & \dots, & W_h^\text{O}
\end{bmatrix}
$



In [6]:
import tiktoken

tokenizer = tiktoken.get_encoding('gpt2')

In [62]:
vocab_size = tokenizer.n_vocab # 50257
d_model = 512

embedding_matrix = nn.Embedding(num_embeddings=vocab_size, embedding_dim=d_model)

def tokenize_text(text):
    token_ids = tokenizer.encode(text)
    embeddings = embedding_matrix(torch.stack([torch.tensor(token_ids)], dim=0))
    return token_ids, embeddings

def tokenize_batch(texts):
    token_ids_list = [tokenizer.encode(text) for text in texts]

    # need the max text size out of all the texts
    max_seq_len = max([len(token_ids) for token_ids in token_ids_list])

    # pad all the texts to the max sequence length (for batch processing)
    padded_token_ids = []
    for ids in token_ids_list:
        padded_ids = ids + [0] * (max_seq_len - len(ids))  # Padding with 0s
        padded_token_ids.append(padded_ids)

    # Convert to tensor and get embeddings
    tokens_tensor = torch.tensor(padded_token_ids)
    embeddings = embedding_matrix(tokens_tensor)

    return token_ids_list, embeddings

def decode_text(token_ids):
    return tokenizer.decode(token_ids)

def decode_batch(token_ids_list):
    return [decode_text(token_ids) for token_ids in token_ids_list]

In [63]:
input_text = []
input_text1 = 'This is a keyboard'
input_text2 = 'A nice coffee cup'
input_text.append(input_text1)
input_text.append(input_text2)

In [60]:
# for a single text
token_ids_single, input_embeddings_single = tokenize_text(input_text[0])
print("\nFor a single text:")
print(input_embeddings_single.shape)
print(input_embeddings_single)
print(token_ids_single)

# for batched processing
token_ids, input_embeddings = tokenize_batch(input_text)

# batch size, sequence length (i.e., number of words), embedding dimension
print("\nFor batched processing:")
print(input_embeddings.shape)
print(input_embeddings)
print(token_ids)



For a single text:
torch.Size([1, 4, 512])
tensor([[[ 0.0444,  1.0484,  1.3557,  ..., -0.8322,  0.7427, -1.7000],
         [ 1.0631, -0.8056, -3.3340,  ..., -0.2969,  0.5532, -0.0959],
         [ 0.3199,  0.8923, -0.9175,  ..., -0.0884,  1.0423, -0.9149],
         [ 0.6791, -1.2112,  3.0816,  ..., -0.1510, -1.8448,  0.3131]]],
       grad_fn=<EmbeddingBackward0>)
[1212, 318, 257, 10586]

For batched processing:
torch.Size([2, 4, 512])
tensor([[[ 0.0444,  1.0484,  1.3557,  ..., -0.8322,  0.7427, -1.7000],
         [ 1.0631, -0.8056, -3.3340,  ..., -0.2969,  0.5532, -0.0959],
         [ 0.3199,  0.8923, -0.9175,  ..., -0.0884,  1.0423, -0.9149],
         [ 0.6791, -1.2112,  3.0816,  ..., -0.1510, -1.8448,  0.3131]],

        [[-0.1444, -0.6360, -0.8506,  ..., -0.4992, -0.8969, -0.5498],
         [-0.4954, -0.9754,  0.8146,  ...,  1.6291, -0.8691,  1.2290],
         [-1.2850,  0.4737, -0.5718,  ..., -1.0871, -1.0541, -1.4151],
         [-0.6142, -1.2674,  0.0843,  ..., -1.4956, -1.5690, 

In [66]:
print("\nDecoded texts:")
print(decode_text(token_ids_single))
print(decode_batch(token_ids))


Decoded texts:
This is a keyboard
['This is a keyboard', 'A nice coffee cup']


Input embeddings -> DONE

### Let's do some positional encoding now

In [11]:
def positional_encoding_simple(pos: int, i: int, d_model=d_model):
    if i % 2 == 0:
        return torch.sin(torch.tensor(pos) / torch.pow(torch.tensor(10000), (2*i) / d_model))
    else:
        return torch.cos(torch.tensor(pos) / torch.pow(torch.tensor(10000), (2*i) / d_model))

this was a very simple function to understand the positional encoding. However, this helps calculate the positional encoding for a single position and a single dimension. Of course, I can always expand this, but instead of a loop, I think it's better to use vectorized operations.

In [67]:
input_embeddings.shape

torch.Size([2, 4, 512])

In [68]:
# vectorized and scalable version

def positional_encoding_original_paper(input_embeddings):
    batch, seq_len, d_model = input_embeddings.shape
    device = input_embeddings.device
    
    # Create position and dimension indices
    pos = torch.arange(seq_len, dtype=torch.float32, device=device).unsqueeze(1)
    dim = torch.arange(d_model, dtype=torch.float32, device=device)
    
    # Compute angle rates
    angle_rates = pos / (10000 ** (2*dim/d_model))
    
    # Initialize encoding matrix
    pe = torch.zeros(seq_len, d_model, device=device)
    
    # Apply sine to even indices, cosine to odd indices
    pe[:, 0::2] = torch.sin(angle_rates[:, 0::2])
    pe[:, 1::2] = torch.cos(angle_rates[:, 1::2])
    
    # Add batch dimension and return
    return pe.unsqueeze(0).expand(batch, -1, -1) + input_embeddings

final_embeddings = positional_encoding_original_paper(input_embeddings)

print(input_embeddings)
print(final_embeddings)

tensor([[[ 0.0444,  1.0484,  1.3557,  ..., -0.8322,  0.7427, -1.7000],
         [ 1.0631, -0.8056, -3.3340,  ..., -0.2969,  0.5532, -0.0959],
         [ 0.3199,  0.8923, -0.9175,  ..., -0.0884,  1.0423, -0.9149],
         [ 0.6791, -1.2112,  3.0816,  ..., -0.1510, -1.8448,  0.3131]],

        [[-0.1444, -0.6360, -0.8506,  ..., -0.4992, -0.8969, -0.5498],
         [-0.4954, -0.9754,  0.8146,  ...,  1.6291, -0.8691,  1.2290],
         [-1.2850,  0.4737, -0.5718,  ..., -1.0871, -1.0541, -1.4151],
         [-0.6142, -1.2674,  0.0843,  ..., -1.4956, -1.5690, -0.5409]]],
       grad_fn=<EmbeddingBackward0>)
tensor([[[ 0.0444,  2.0484,  1.3557,  ...,  0.1678,  0.7427, -0.7000],
         [ 1.9046, -0.2359, -2.5320,  ...,  0.7031,  0.5532,  0.9041],
         [ 1.2292,  0.5414,  0.0406,  ...,  0.9116,  1.0423,  0.0851],
         [ 0.8202, -2.1807,  3.4244,  ...,  0.8490, -1.8448,  1.3131]],

        [[-0.1444,  0.3640, -0.8506,  ...,  0.5008, -0.8969,  0.4502],
         [ 0.3461, -0.4057,  1.616

In [69]:
print(positional_encoding_simple(0, 1) + input_embeddings[0][0][1])
print(positional_encoding_original_paper(input_embeddings)[0][0][1])

tensor(2.0484, grad_fn=<AddBackward0>)
tensor(2.0484, grad_fn=<SelectBackward0>)


An even more scalable version for the positional encoding is to use the following formula:

$$
PE_{(pos, i)} = \begin{cases} 
\sin\left(pos \cdot \exp\left(-\frac{2i}{d_{\text{model}}} \ln (10000)\right)\right) & \text{if } i \text{ even} \\
\cos\left(pos \cdot \exp\left(-\frac{2i}{d_{\text{model}}} \ln (10000)\right)\right) & \text{if } i \text{ odd}
\end{cases}
$$

compared to the original paper's formula:

$$
PE_{(pos, i)} = \begin{cases} 
\sin\left(\frac{pos}{10000^{2i/d_{\text{model}}}}\right) & \text{if } i \text{ even} \\
\cos\left(\frac{pos}{10000^{2i/d_{\text{model}}}}\right) & \text{if } i \text{ odd}
\end{cases}
$$

Proof of Equivalence:
$$
\frac{pos}{10000^{2i/d_{\text{model}}}} = pos \cdot \exp\left(-\frac{2i}{d_{\text{model}}} \ln (10000)\right)
$$
 
This holds because:

$$
10000^x = e^{x \ln (10000)} \Rightarrow \frac{1}{10000} = e^{-\ln (10000)}
$$

In code:

In [70]:
input_embeddings.shape

torch.Size([2, 4, 512])

In [87]:
def positional_encoding(input_embeddings):
    batch, seq_len, d_model = input_embeddings.shape
    pos = torch.arange(seq_len).unsqueeze(1)
    dim = torch.arange(d_model)

    angle_rates = pos * torch.exp((-2 * dim * torch.log(torch.tensor(10000))) / d_model)

    pe = torch.zeros(seq_len, d_model) # positional encoding initialized
    pe[:, 0::2] = torch.sin(angle_rates[:, 0::2])
    pe[:, 1::2] = torch.cos(angle_rates[:, 1::2])
    
    # add batch dimension
    pe = pe.unsqueeze(0).expand(batch, -1, -1) + input_embeddings
    return pe

positional_encoding(input_embeddings)

tensor([[[ 0.0444,  2.0484,  1.3557,  ...,  0.1678,  0.7427, -0.7000],
         [ 1.9046, -0.2359, -2.5320,  ...,  0.7031,  0.5532,  0.9041],
         [ 1.2292,  0.5414,  0.0406,  ...,  0.9116,  1.0423,  0.0851],
         [ 0.8202, -2.1807,  3.4244,  ...,  0.8490, -1.8448,  1.3131]],

        [[-0.1444,  0.3640, -0.8506,  ...,  0.5008, -0.8969,  0.4502],
         [ 0.3461, -0.4057,  1.6166,  ...,  2.6291, -0.8691,  2.2290],
         [-0.3757,  0.1228,  0.3864,  ..., -0.0871, -1.0541, -0.4151],
         [-0.4731, -2.2369,  0.4271,  ..., -0.4956, -1.5690,  0.4591]]],
       grad_fn=<AddBackward0>)

In [100]:
# Comparison

print(f"Encoded embedding using simple function: {positional_encoding_simple(0, 1) + input_embeddings[0][0][1]}")
print(f"Encoded embedding using original paper's formula: {positional_encoding_original_paper(input_embeddings)[0][0][1]}")
print(f"Encoded embedding using the vectorized and scalable version: {positional_encoding(input_embeddings)[0][0][1]}")

positional_encoding(input_embeddings)[0][0][1] == positional_encoding_simple(0, 1) + input_embeddings[0][0][1] == positional_encoding_original_paper(input_embeddings)[0][0][1] == positional_encoding(input_embeddings)[0][0][1]

Encoded embedding using simple function: 2.0483908653259277
Encoded embedding using original paper's formula: 2.0483908653259277
Encoded embedding using the vectorized and scalable version: 2.0483908653259277


tensor(True)

Everything is the same!